# use Nginx Base Image
FROM nginx:alpine

# Copy all static files to /usr/share/nginx/html
# This is the default directory for nginx

# expose port 80

# Nginx runs in the foreground by default
# CMD is already defined in the base image