# Official Image for OpenJDK binaries built by Eclipse Temurin.
FROM eclipse-temurin:17-jdk

# set working directory

# copy Hello.java to working dir

# Compile into /app/build

# start Hello class using --class-path
